/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package WzorceSklep.Data.Klient;

import WzorceSklep.DAOFactory;
import WzorceSklep.Data.AdresOsoby;
import WzorceSklep.Util;

import javax.swing.*;
import javax.swing.text.MaskFormatter;
import java.awt.*;
import java.text.ParseException;

/**
 *
 * @author Krzysztof
 */
public class DialogDodajKlienta extends javax.swing.JDialog 
{
    public static final String MIEJSCOWOSC_PLACEHOLDER = "Miejscowość";
    public static final String IMIE_PLACEHOLDER = "Imię";
    public static final String MAIL_PLACEHOLDER = "Mail";
    public static final String KRAJ_PLACEHOLDER = "Kraj";
    public static final String ULICA_PLACEHOLDER = "Ulica";
    public static final String NAZWISKO_PLACEHOLDER = "Nazwa klienta / Nazwisko";
    public static final String NR_LOKALU_PLACEHOLDER = "Nr lokalu";
    public static final String NR_DOMU_PLACEHOLDER = "Nr domu";
    public static final String POCZTA_PLACEHOLDER = "Poczta";
    public static final String TELEFON_PLACEHOLDER = "Telefon";
    private JFormattedTextField.AbstractFormatter format;

    /**
     * Creates new form DialogDodajKlienta
     */
    public DialogDodajKlienta(Frame parent) {
        super(parent, true);
        try
        {
            format = new MaskFormatter("##-###");
        }
        catch(ParseException e)
        {
            System.out.println("Proszę nie grzebać w konstruktorze DialogDodajKlienta");
        }
        initComponents();
        wypelnijPola.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telefonField = new javax.swing.JTextField();
        pocztaField = new javax.swing.JTextField();
        wypelnijPola = new javax.swing.JLabel();
        miejscowoscField = new javax.swing.JTextField();
        kodLabel = new javax.swing.JLabel();
        kodPocztowyField = new javax.swing.JFormattedTextField(format);
        nrdomuField = new javax.swing.JTextField();
        nrlokaluField = new javax.swing.JTextField();
        nazwiskoField = new javax.swing.JTextField();
        ulicaField = new javax.swing.JTextField();
        krajField = new javax.swing.JTextField();
        mailField = new javax.swing.JTextField();
        imieField = new javax.swing.JTextField();
        utworz = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        telefonField.setText("Telefon");
        telefonField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                telefonFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                telefonFieldFocusLost(evt);
            }
        });

        pocztaField.setText("Poczta");
        pocztaField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pocztaFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pocztaFieldFocusLost(evt);
            }
        });

        wypelnijPola.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        wypelnijPola.setForeground(new java.awt.Color(255, 0, 0));
        wypelnijPola.setText("Niepoprawne lub niekompletne dane - popraw!");

        miejscowoscField.setText("Miejscowość");
        miejscowoscField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                miejscowoscFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                miejscowoscFieldFocusLost(evt);
            }
        });

        kodLabel.setText("Kod pocztowy:");

        kodPocztowyField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                kodPocztowyFieldFocusGained(evt);
            }
        });

        nrdomuField.setText("Nr domu");
        nrdomuField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nrdomuFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nrdomuFieldFocusLost(evt);
            }
        });

        nrlokaluField.setText("Nr lokalu");
        nrlokaluField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nrlokaluFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nrlokaluFieldFocusLost(evt);
            }
        });

        nazwiskoField.setText("Nazwisko");
        nazwiskoField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nazwiskoFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nazwiskoFieldFocusLost(evt);
            }
        });

        ulicaField.setText("Ulica");
        ulicaField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ulicaFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ulicaFieldFocusLost(evt);
            }
        });

        krajField.setText("Kraj");
        krajField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                krajFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                krajFieldFocusLost(evt);
            }
        });

        mailField.setText("Mail");
        mailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mailFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mailFieldFocusLost(evt);
            }
        });

        imieField.setText("Imię");
        imieField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                imieFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                imieFieldFocusLost(evt);
            }
        });

        utworz.setText("Zapisz");
        utworz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utworzActionPerformed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Vijaya", 0, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Dodawanie nowego klienta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(wypelnijPola)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(utworz, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ulicaField)
                                    .addGap(18, 18, 18)
                                    .addComponent(nrdomuField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(nrlokaluField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(telefonField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(26, 26, 26)
                                            .addComponent(mailField))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(kodLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                            .addComponent(kodPocztowyField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(pocztaField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(krajField, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(miejscowoscField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nazwiskoField, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(imieField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nazwiskoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imieField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ulicaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nrdomuField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nrlokaluField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kodLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kodPocztowyField)
                    .addComponent(pocztaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(miejscowoscField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(krajField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wypelnijPola)
                    .addComponent(utworz))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void telefonFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonFieldFocusGained
        telefonField.selectAll();
    }//GEN-LAST:event_telefonFieldFocusGained

    private void telefonFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonFieldFocusLost
        if (telefonField.getText().equals("")) {
            telefonField.setText(TELEFON_PLACEHOLDER);
        }
    }//GEN-LAST:event_telefonFieldFocusLost

    private void pocztaFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pocztaFieldFocusGained
        pocztaField.selectAll();
    }//GEN-LAST:event_pocztaFieldFocusGained

    private void pocztaFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pocztaFieldFocusLost
        if (pocztaField.getText().equals("")) {
            pocztaField.setText(POCZTA_PLACEHOLDER);
        }
    }//GEN-LAST:event_pocztaFieldFocusLost

    private void miejscowoscFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_miejscowoscFieldFocusGained
        miejscowoscField.selectAll();
    }//GEN-LAST:event_miejscowoscFieldFocusGained

    private void miejscowoscFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_miejscowoscFieldFocusLost
        if (miejscowoscField.getText().equals("")) {
            miejscowoscField.setText(MIEJSCOWOSC_PLACEHOLDER);
        }
    }//GEN-LAST:event_miejscowoscFieldFocusLost

    private void kodPocztowyFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kodPocztowyFieldFocusGained
        kodPocztowyField.selectAll();
    }//GEN-LAST:event_kodPocztowyFieldFocusGained

    private void nrdomuFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nrdomuFieldFocusGained
        nrdomuField.selectAll();
    }//GEN-LAST:event_nrdomuFieldFocusGained

    private void nrdomuFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nrdomuFieldFocusLost
        if (nrdomuField.getText().equals("")) {
            nrdomuField.setText(NR_DOMU_PLACEHOLDER);
        }
    }//GEN-LAST:event_nrdomuFieldFocusLost

    private void nrlokaluFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nrlokaluFieldFocusGained
        nrlokaluField.selectAll();
    }//GEN-LAST:event_nrlokaluFieldFocusGained

    private void nrlokaluFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nrlokaluFieldFocusLost
        if (nrlokaluField.getText().equals("")) {
            nrlokaluField.setText(NR_LOKALU_PLACEHOLDER);
        }
    }//GEN-LAST:event_nrlokaluFieldFocusLost

    private void nazwiskoFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nazwiskoFieldFocusGained
        nazwiskoField.selectAll();
    }//GEN-LAST:event_nazwiskoFieldFocusGained

    private void nazwiskoFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nazwiskoFieldFocusLost
        if (nazwiskoField.getText().equals("")) {
            nazwiskoField.setText(NAZWISKO_PLACEHOLDER);
        }
    }//GEN-LAST:event_nazwiskoFieldFocusLost

    private void ulicaFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ulicaFieldFocusGained
        ulicaField.selectAll();
    }//GEN-LAST:event_ulicaFieldFocusGained

    private void ulicaFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ulicaFieldFocusLost
        if (ulicaField.getText().equals("")) {
            ulicaField.setText(ULICA_PLACEHOLDER);
        }
    }//GEN-LAST:event_ulicaFieldFocusLost

    private void krajFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_krajFieldFocusGained
        krajField.selectAll();
    }//GEN-LAST:event_krajFieldFocusGained

    private void krajFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_krajFieldFocusLost
        if (krajField.getText().equals("")) {
            krajField.setText(KRAJ_PLACEHOLDER);
        }
    }//GEN-LAST:event_krajFieldFocusLost

    private void mailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailFieldFocusGained
        mailField.selectAll();
    }//GEN-LAST:event_mailFieldFocusGained

    private void mailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailFieldFocusLost
        if (mailField.getText().equals("")) {
            mailField.setText(MAIL_PLACEHOLDER);
        }
    }//GEN-LAST:event_mailFieldFocusLost

    private void imieFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_imieFieldFocusGained
        imieField.selectAll();
    }//GEN-LAST:event_imieFieldFocusGained

    private void imieFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_imieFieldFocusLost
        if (imieField.getText().equals("")) {
            imieField.setText(IMIE_PLACEHOLDER);
        }
    }//GEN-LAST:event_imieFieldFocusLost



    private boolean nieWypelnione() {
        return  nazwiskoField.getText().equals(NAZWISKO_PLACEHOLDER) ||
                !kodPocztowyField.isEditValid() ||
                miejscowoscField.getText().equals(MIEJSCOWOSC_PLACEHOLDER) ||
                pocztaField.getText().equals(POCZTA_PLACEHOLDER) ||
                krajField.getText().equals(KRAJ_PLACEHOLDER);
    }
    private void utworzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utworzActionPerformed

        wypelnijPola.setVisible(false);
        if(nieWypelnione())
        {
            wypelnijPola.setVisible(true);
            return;
        }
        Klient klient = new Klient();
        loadDataFromTextFields(klient);
        
        //System.out.println(inputStrings[7]);


        try {

            if (!nrdomuField.getText().equals(NR_DOMU_PLACEHOLDER)) {
                klient.getAdres().setNrDomu(Integer.valueOf(nrdomuField.getText()));
            }
            if (!nrlokaluField.getText().equals(NR_LOKALU_PLACEHOLDER)) {
                klient.getAdres().setNrLokalu(Integer.valueOf(nrlokaluField.getText()));
            }
            new DAOFactory().getKlientDAO().insert(klient);

        } catch (Exception e) {
            wypelnijPola.setVisible(true);
            Util.showErrorDialog(this, e);
            return;
        }
/*        try {
            CallableStatement proc = connection.prepareCall("{call DodajKlienta(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)}");
            for (int i = 0; i < 8; i++) 
            {
                //System.out.println(inputStrings[i]);
                if (inputStrings[i].equals("")) {
                    wypelnijPola.setVisible(true);
                    return;
                }
                proc.setString(i + 1, inputStrings[i]);
            }
            for (int i = 0; i < 3; i++) {
                proc.setInt(i + 8, inputInts[i]);
            }
            
            proc.execute();
            proc.close();
        } catch (Exception e) {
            e.printStackTrace();
        } finally {*/
            dispose();
//        }
    }//GEN-LAST:event_utworzActionPerformed

    private void loadDataFromTextFields(Klient klient) {
        klient.setAdres(new AdresOsoby());
        if (!imieField.getText().equals(IMIE_PLACEHOLDER)) {
            klient.setImie(imieField.getText());
        }
        klient.setNazwisko(nazwiskoField.getText());
        klient.getAdres().setKodPocztowy(kodPocztowyField.getText());
        klient.getAdres().setKraj(krajField.getText());
        if (!ulicaField.getText().equals(ULICA_PLACEHOLDER)) {
            klient.getAdres().setUlica(ulicaField.getText());
        }
        klient.getAdres().setMiejscowosc(miejscowoscField.getText());
        if (!pocztaField.getText().equals(POCZTA_PLACEHOLDER)) {
            klient.getAdres().setPoczta(pocztaField.getText());
        }
        else {
            klient.getAdres().setPoczta(klient.getAdres().getMiejscowosc());
        }
        if (!mailField.getText().equals(MAIL_PLACEHOLDER)) {
            klient.setMail(mailField.getText());
        }
        if (!telefonField.getText().equals(TELEFON_PLACEHOLDER)) {
            klient.setTelefon(telefonField.getText());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogDodajKlienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogDodajKlienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogDodajKlienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogDodajKlienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        /*java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                DialogDodajKlienta dialog = new DialogDodajKlienta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });*/
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField imieField;
    private javax.swing.JLabel kodLabel;
    private javax.swing.JFormattedTextField kodPocztowyField;
    private javax.swing.JTextField krajField;
    private javax.swing.JTextField mailField;
    private javax.swing.JTextField miejscowoscField;
    private javax.swing.JTextField nazwiskoField;
    private javax.swing.JTextField nrdomuField;
    private javax.swing.JTextField nrlokaluField;
    private javax.swing.JTextField pocztaField;
    private javax.swing.JTextField telefonField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField ulicaField;
    private javax.swing.JButton utworz;
    private javax.swing.JLabel wypelnijPola;
    // End of variables declaration//GEN-END:variables
}
