package WzorceSklep.Data.Klient;/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

import WzorceSklep.DAOFactory;
import WzorceSklep.Data.AdresOsoby;
import WzorceSklep.GUI.RefreshableJFrame;
import WzorceSklep.Util;

import javax.swing.*;
import javax.swing.text.MaskFormatter;
import java.awt.*;
import java.sql.SQLException;
import java.text.ParseException;

/**
 *
 * @author KrzysztofD
 */
public class EdytujKlientaDialog extends javax.swing.JDialog {

    private final String IMIE_PLACEHOLDER = "";
    private final String NAZWISKO_PLACEHOLDER = "";
    private final String ULICA_PLACEHOLDER = "";
    private final String NR_DOMU_PLACEHOLDER = "";
    private final String NR_LOKALU_PLACEHOLDER = "";
    private final String POCZTA_PLACEHOLDER = "";
    private final String MIEJSCOWOSC_PLACEHOLDER = "";
    private final String TELEFON_PLACEHOLDER = "";
    private final String MAIL_PLACEHOLDER = "";
    private final String KRAJ_PLACEHOLDER = "";
    private Klient klient;
    private JFormattedTextField.AbstractFormatter format;

    /**
     * Creates new form EdytujKlientaDialog
     */
    public EdytujKlientaDialog(Frame parent, int idKlienta, DAOFactory daoFactory) {
        super(parent, true);
        initComponents();
        nieWypelnioneLabel.setVisible(false);
        try
        {
            format = new MaskFormatter("##-###");
        }
        catch(ParseException e)
        {
            System.out.println("Proszę nie grzebać w konstruktorze DialogEdytujKlienta");
        }
        klient = InitKlient(daoFactory,idKlienta);
    }

    private Klient InitKlient(DAOFactory daoFactory, int idKlienta) {
        Klient wynik = new Klient();

        try {
            wynik = daoFactory.getKlientDAO().getById(idKlienta);
            imieField.setText(wynik.getImie());
            nazwiskoField.setText(wynik.getNazwisko());
            mailField.setText(wynik.getMail());
            telefonField.setText(wynik.getTelefon());

            AdresOsoby adres = wynik.getAdres();
            ulicaField.setText(adres.getUlica());
            kodPocztowyField.setText(adres.getKodPocztowy());
            pocztaField.setText(adres.getPoczta());
            miejscowoscField.setText(adres.getMiejscowosc());
            krajField.setText(adres.getKraj());
            String nrDomuText = (adres.getNrDomu() == null) ? "" : adres.getNrDomu().toString();
            nrdomuField.setText(nrDomuText);
            String nrLokaluText = (adres.getNrLokalu() == null) ? "" : adres.getNrLokalu().toString();
            nrlokaluField.setText(nrLokaluText);


        } catch (SQLException e) {
            e.printStackTrace();  //To change body of catch statement use File | Settings | File Templates.
        }

        return wynik;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        imieField = new javax.swing.JTextField();
        nazwiskoField = new javax.swing.JTextField();
        ulicaField = new javax.swing.JTextField();
        nrdomuField = new javax.swing.JTextField();
        nrlokaluField = new javax.swing.JTextField();
        kodLabel = new javax.swing.JLabel();
        kodPocztowyField = new javax.swing.JFormattedTextField(format);
        pocztaField = new javax.swing.JTextField();
        miejscowoscField = new javax.swing.JTextField();
        telefonField = new javax.swing.JTextField();
        mailField = new javax.swing.JTextField();
        krajField = new javax.swing.JTextField();
        utworz = new javax.swing.JButton();
        nieWypelnioneLabel = new javax.swing.JLabel();
        skasujButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Vijaya", 0, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Zmiana danych klienta");

        imieField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                imieFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                imieFieldFocusLost(evt);
            }
        });

        nazwiskoField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nazwiskoFieldFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                nazwiskoFieldFocusGained(evt);
            }
        });

        ulicaField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ulicaFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ulicaFieldFocusLost(evt);
            }
        });

        nrdomuField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nrdomuFieldFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                nrdomuFieldFocusGained(evt);
            }
        });

        nrlokaluField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nrlokaluFieldFocusLost(evt);
            }

            public void focusGained(java.awt.event.FocusEvent evt) {
                nrlokaluFieldFocusGained(evt);
            }
        });

        kodLabel.setText("Kod pocztowy:");

        kodPocztowyField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                kodPocztowyFieldFocusGained(evt);
            }
        });

        pocztaField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pocztaFieldFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                pocztaFieldFocusGained(evt);
            }
        });

        miejscowoscField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                miejscowoscFieldFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                miejscowoscFieldFocusGained(evt);
            }
        });

        telefonField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                telefonFieldFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                telefonFieldFocusGained(evt);
            }
        });

        mailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                mailFieldFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                mailFieldFocusGained(evt);
            }
        });

        krajField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                krajFieldFocusLost(evt);
            }

            public void focusGained(java.awt.event.FocusEvent evt) {
                krajFieldFocusGained(evt);
            }
        });

        utworz.setText("Zapisz");
        utworz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utworzActionPerformed(evt);
            }
        });

        nieWypelnioneLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nieWypelnioneLabel.setForeground(new java.awt.Color(255, 51, 51));
        nieWypelnioneLabel.setText("Niepoprawne lub niekompletne dane - popraw!");

        skasujButton.setText("Skasuj");
        skasujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skasujButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nazwiskoField, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(imieField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(kodLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kodPocztowyField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pocztaField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(miejscowoscField, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(telefonField)
                        .addGap(18, 18, 18)
                        .addComponent(mailField, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(krajField, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ulicaField)
                        .addGap(18, 18, 18)
                        .addComponent(nrdomuField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nrlokaluField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nieWypelnioneLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(skasujButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(utworz, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imieField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nazwiskoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nrlokaluField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nrdomuField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ulicaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(miejscowoscField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pocztaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kodPocztowyField)
                    .addComponent(kodLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(krajField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(nieWypelnioneLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(utworz)
                        .addComponent(skasujButton))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(225, 225, 225)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imieFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_imieFieldFocusLost
        if (imieField.getText().equals("")) {
            imieField.setText(IMIE_PLACEHOLDER);
        }
    }//GEN-LAST:event_imieFieldFocusLost

    private void imieFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_imieFieldFocusGained
        imieField.selectAll();
    }//GEN-LAST:event_imieFieldFocusGained

    private void nazwiskoFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nazwiskoFieldFocusLost
        if (nazwiskoField.getText().equals("")) {
            nazwiskoField.setText(NAZWISKO_PLACEHOLDER);
        }
    }//GEN-LAST:event_nazwiskoFieldFocusLost

    private void nazwiskoFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nazwiskoFieldFocusGained
        nazwiskoField.selectAll();
    }//GEN-LAST:event_nazwiskoFieldFocusGained

    private void ulicaFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ulicaFieldFocusLost
        if (ulicaField.getText().equals("")) {
            ulicaField.setText(ULICA_PLACEHOLDER);
        }
    }//GEN-LAST:event_ulicaFieldFocusLost

    private void ulicaFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ulicaFieldFocusGained
        ulicaField.selectAll();
    }//GEN-LAST:event_ulicaFieldFocusGained

    private void nrdomuFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nrdomuFieldFocusLost
        if (nrdomuField.getText().equals("")) {
            nrdomuField.setText(NR_DOMU_PLACEHOLDER);
        }
    }//GEN-LAST:event_nrdomuFieldFocusLost

    private void nrdomuFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nrdomuFieldFocusGained
        nrdomuField.selectAll();
    }//GEN-LAST:event_nrdomuFieldFocusGained

    private void nrlokaluFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nrlokaluFieldFocusLost
        if (nrlokaluField.getText().equals("")) {
            nrlokaluField.setText(NR_LOKALU_PLACEHOLDER);
        }
    }//GEN-LAST:event_nrlokaluFieldFocusLost

    private void nrlokaluFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nrlokaluFieldFocusGained
        nrlokaluField.selectAll();
    }//GEN-LAST:event_nrlokaluFieldFocusGained

    private void kodPocztowyFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kodPocztowyFieldFocusGained
        kodPocztowyField.selectAll();
    }//GEN-LAST:event_kodPocztowyFieldFocusGained

    private void pocztaFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pocztaFieldFocusLost
        if (pocztaField.getText().equals("")) {
            pocztaField.setText(POCZTA_PLACEHOLDER);
        }
    }//GEN-LAST:event_pocztaFieldFocusLost

    private void pocztaFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pocztaFieldFocusGained
        pocztaField.selectAll();
    }//GEN-LAST:event_pocztaFieldFocusGained

    private void miejscowoscFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_miejscowoscFieldFocusLost
        if (miejscowoscField.getText().equals("")) {
            miejscowoscField.setText(MIEJSCOWOSC_PLACEHOLDER);
        }
    }//GEN-LAST:event_miejscowoscFieldFocusLost

    private void miejscowoscFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_miejscowoscFieldFocusGained
        miejscowoscField.selectAll();
    }//GEN-LAST:event_miejscowoscFieldFocusGained

    private void telefonFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonFieldFocusLost
        if (telefonField.getText().equals("")) {
            telefonField.setText(TELEFON_PLACEHOLDER);
        }
    }//GEN-LAST:event_telefonFieldFocusLost

    private void telefonFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonFieldFocusGained
        telefonField.selectAll();
    }//GEN-LAST:event_telefonFieldFocusGained

    private void mailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailFieldFocusLost
        if (mailField.getText().equals("")) {
            mailField.setText(MAIL_PLACEHOLDER);
        }
    }//GEN-LAST:event_mailFieldFocusLost

    private void mailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailFieldFocusGained
        mailField.selectAll();
    }//GEN-LAST:event_mailFieldFocusGained

    private void krajFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_krajFieldFocusLost
        if (krajField.getText().equals("")) {
            krajField.setText(KRAJ_PLACEHOLDER);
        }
    }//GEN-LAST:event_krajFieldFocusLost

    private void krajFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_krajFieldFocusGained
        krajField.selectAll();
    }//GEN-LAST:event_krajFieldFocusGained



    private void loadDataFromTextFields() {
        klient = new Klient(klient.getID());
        klient.setImie(imieField.getText());
        klient.setNazwisko(nazwiskoField.getText());
        if (!ulicaField.getText().equals(ULICA_PLACEHOLDER)) {
            klient.getAdres().setUlica(ulicaField.getText());
        }
        klient.getAdres().setKodPocztowy(kodPocztowyField.getText());
        klient.getAdres().setPoczta(pocztaField.getText());
        klient.getAdres().setMiejscowosc(miejscowoscField.getText());
        klient.getAdres().setKraj(krajField.getText());
        klient.setMail(mailField.getText());
    }

    private void utworzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utworzActionPerformed
        if(nieWypelnione())
        {
            nieWypelnioneLabel.setVisible(true);
            return;
        }
        loadDataFromTextFields();

        //System.out.println(inputStrings[7]);

        try {
            klient.setTelefon(telefonField.getText());
            if (!nrdomuField.getText().equals(NR_DOMU_PLACEHOLDER)) {
                klient.getAdres().setNrDomu(Integer.valueOf(nrdomuField.getText()));
            }
            if (!nrlokaluField.getText().equals(NR_LOKALU_PLACEHOLDER)) {
                klient.getAdres().setNrLokalu(Integer.valueOf(nrlokaluField.getText()));
            }
            new DAOFactory().getKlientDAO().update(klient);

        } catch (Exception e) {
            e.printStackTrace();  //To change body of catch statement use File | Settings | File Templates.
            return;
        }
        /*        try {
            CallableStatement proc = connection.prepareCall("{call DodajKlienta(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)}");
            for (int i = 0; i < 8; i++)
            {
                //System.out.println(inputStrings[i]);
                if (inputStrings[i].equals("")) {
                    wypelnijPola.setVisible(true);
                    return;
                }
                proc.setString(i + 1, inputStrings[i]);
            }
            for (int i = 0; i < 3; i++) {
                proc.setInt(i + 8, inputInts[i]);
            }

            proc.execute();
            proc.close();
        } catch (Exception e) {
            e.printStackTrace();
        } finally {*/
            dispose();
            //        }
    }//GEN-LAST:event_utworzActionPerformed

    private void skasujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skasujButtonActionPerformed
        if(showConfirmationDialog(this, klient.getName())==JOptionPane.YES_OPTION)
            try {
                new DAOFactory().getKlientDAO().delete(klient.getID());
                dispose();
            } catch (SQLException e) {
                e.printStackTrace();  //To change body of catch statement use File | Settings | File Templates.
                Util.showErrorDialog(this,e);
            }
    }//GEN-LAST:event_skasujButtonActionPerformed

    private static int showConfirmationDialog(Component owner, String name) {
        final String[] options = { "Tak", "Nie" };
        return JOptionPane.showOptionDialog(owner,
                String.format("Czy na pewno chcesz usunąć %s?", name),
                "Potwierdzenie usunięcia",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE,
                null, options, options[1]);
    }

    private boolean nieWypelnione() {
        return  nazwiskoField.getText().equals(NAZWISKO_PLACEHOLDER) ||
                !kodPocztowyField.isEditValid() ||
                miejscowoscField.getText().equals(MIEJSCOWOSC_PLACEHOLDER) ||
                pocztaField.getText().equals(POCZTA_PLACEHOLDER) ||
                krajField.getText().equals(KRAJ_PLACEHOLDER);
    }

    public static void main(final RefreshableJFrame parent, final int idKlienta, final DAOFactory daoFactory) {
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EdytujKlientaDialog dialog = new EdytujKlientaDialog(parent, idKlienta, daoFactory);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosed(java.awt.event.WindowEvent e) {
                        parent.refreshCurrentWindow();
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField imieField;
    private javax.swing.JLabel kodLabel;
    private javax.swing.JFormattedTextField kodPocztowyField;
    private javax.swing.JTextField krajField;
    private javax.swing.JTextField mailField;
    private javax.swing.JTextField miejscowoscField;
    private javax.swing.JTextField nazwiskoField;
    private javax.swing.JLabel nieWypelnioneLabel;
    private javax.swing.JTextField nrdomuField;
    private javax.swing.JTextField nrlokaluField;
    private javax.swing.JTextField pocztaField;
    private javax.swing.JButton skasujButton;
    private javax.swing.JTextField telefonField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField ulicaField;
    private javax.swing.JButton utworz;
    // End of variables declaration//GEN-END:variables
}
