/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package WzorceSklep.Data.Produkt;

import WzorceSklep.DAOFactory;

import java.awt.*;
import java.math.BigDecimal;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JFormattedTextField;

/**
 *
 * @author Karolina
 */
public class DialogDodajProdukt extends javax.swing.JDialog {

    JFormattedTextField.AbstractFormatter format;

    /**
     * Creates new form DialogDodajProdukt
     */
    public DialogDodajProdukt(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        wypelnijPola.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        iloscField = new javax.swing.JTextField();
        typField = new javax.swing.JTextField();
        specyfikacjaField = new javax.swing.JTextField();
        wypelnijPola = new javax.swing.JLabel();
        cenaField = new javax.swing.JTextField();
        nazwaField = new javax.swing.JTextField();
        utworz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Vijaya", 0, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Dodawanie nowego produktu");

        iloscField.setText("Ilosc");
        iloscField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                iloscFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                iloscFieldFocusLost(evt);
            }
        });

        typField.setText("Typ");
        typField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                typFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                typFieldFocusLost(evt);
            }
        });

        specyfikacjaField.setText("Specyfikacja");
        specyfikacjaField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                specyfikacjaFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                specyfikacjaFieldFocusLost(evt);
            }
        });

        wypelnijPola.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        wypelnijPola.setForeground(new java.awt.Color(255, 0, 0));
        wypelnijPola.setText("Wypełnij wszystkie pola!");

        cenaField.setText("Cena");
        cenaField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cenaFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cenaFieldFocusLost(evt);
            }
        });

        nazwaField.setText("Nazwa");
        nazwaField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nazwaFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nazwaFieldFocusLost(evt);
            }
        });

        utworz.setText("Dodaj");
        utworz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utworzActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(specyfikacjaField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cenaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iloscField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(wypelnijPola, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(374, 374, 374)
                                    .addComponent(utworz, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(typField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nazwaField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(typField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(specyfikacjaField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(wypelnijPola)
                        .addGap(59, 59, 59)
                        .addComponent(utworz))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nazwaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(cenaField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(iloscField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(84, 84, 84))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iloscFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_iloscFieldFocusGained
        iloscField.selectAll();
    }//GEN-LAST:event_iloscFieldFocusGained

    private void iloscFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_iloscFieldFocusLost
        if (iloscField.getText().equals("")) {
            iloscField.setText("Ilosc");
        }
    }//GEN-LAST:event_iloscFieldFocusLost

    private void typFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_typFieldFocusGained
        typField.selectAll();
    }//GEN-LAST:event_typFieldFocusGained

    private void typFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_typFieldFocusLost
        if (typField.getText().equals("")) {
            typField.setText("Typ");
        }
    }//GEN-LAST:event_typFieldFocusLost

    private void specyfikacjaFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_specyfikacjaFieldFocusGained
        specyfikacjaField.selectAll();
    }//GEN-LAST:event_specyfikacjaFieldFocusGained

    private void specyfikacjaFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_specyfikacjaFieldFocusLost
        if (specyfikacjaField.getText().equals("")) {
            specyfikacjaField.setText("Specyfikacja");
        }
    }//GEN-LAST:event_specyfikacjaFieldFocusLost

    private void cenaFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cenaFieldFocusGained
        cenaField.selectAll();
    }//GEN-LAST:event_cenaFieldFocusGained

    private void cenaFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cenaFieldFocusLost
        if (cenaField.getText().equals("")) {
            cenaField.setText("Cena");
        }
    }//GEN-LAST:event_cenaFieldFocusLost

    private void nazwaFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nazwaFieldFocusGained
        nazwaField.selectAll();
    }//GEN-LAST:event_nazwaFieldFocusGained

    private void nazwaFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nazwaFieldFocusLost
        if (nazwaField.getText().equals("")) {
            nazwaField.setText("Nazwa");
        }
    }//GEN-LAST:event_nazwaFieldFocusLost

    private void utworzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utworzActionPerformed

        wypelnijPola.setVisible(false);
        Produkt produkt = new Produkt();

        produkt.typ = typField.getText();
        produkt.specyfikacja = specyfikacjaField.getText();
        produkt.nazwa = nazwaField.getText();
        produkt.cena = new BigDecimal(cenaField.getText());
        produkt.ilosc = new Integer(iloscField.getText());

        try {
            DAOFactory.getProduktyDAO().insert(produkt);
        } catch (SQLException e) {
            e.printStackTrace();  //To change body of catch statement use File | Settings | File Templates.
            wypelnijPola.setVisible(true);
            return;
        }
        dispose();
      
/*        try {
            CallableStatement proc = connection.prepareCall("{call DodajProdukt(?, ?, ?, ?, ?)}");
                proc.setString(1, typ);
                proc.setString(2, specyfikacja);
                proc.setString(3, nazwa);
                proc.setInt(4, cena);
                proc.setInt(5, ilosc);
            proc.execute();
            proc.close();
        } catch (Exception e) {
            e.printStackTrace();
        } finally {*/
//        }
    }//GEN-LAST:event_utworzActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogDodajProdukt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogDodajProdukt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogDodajProdukt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogDodajProdukt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                DialogDodajProdukt dialog = new DialogDodajProdukt(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
        * *
        */
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cenaField;
    private javax.swing.JTextField iloscField;
    private javax.swing.JTextField nazwaField;
    private javax.swing.JTextField specyfikacjaField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField typField;
    private javax.swing.JButton utworz;
    private javax.swing.JLabel wypelnijPola;
    // End of variables declaration//GEN-END:variables
}
