/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package WzorceSklep.Data.Pracownik;

/**
 *
 * @author Krzysztof
 */
import java.sql.CallableStatement;
import java.sql.Connection;
import java.text.ParseException;
import javax.swing.JFormattedTextField.AbstractFormatter;
import javax.swing.text.MaskFormatter;

public class OknoDodajPracownika extends javax.swing.JFrame
{
    AbstractFormatter format;
    Connection connection=null;
    /**
     * Creates new form OknoDodajPracownika
     */
    public OknoDodajPracownika(Connection con) 
    {
        try
        {
            format = new MaskFormatter("##-###");
            connection=con;
            //final OknoDodajPracownika thisframe=this;
            
            /*
            * addWindowListener(new WindowAdapter() 
                {
                @Override
                    public void windowClosing(WindowEvent e)
                    {
                        //thisframe.setVisible(false);
                    }
                });*/
        }
        catch(ParseException e)
        {
            System.out.println("To nie powinno się zdarzyć.");
        }
        initComponents();
        niezgodneHasla.setVisible(false);
        wypelnijPola.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imieField = new javax.swing.JTextField();
        nazwiskoField = new javax.swing.JTextField();
        loginField = new javax.swing.JTextField();
        hasloField = new javax.swing.JPasswordField();
        powtorzField = new javax.swing.JPasswordField();
        telefonField = new javax.swing.JTextField();
        mailField = new javax.swing.JTextField();
        umowaField = new javax.swing.JTextField();
        statusField = new javax.swing.JComboBox();
        utworz = new javax.swing.JButton();
        hasloLabel = new javax.swing.JLabel();
        hasloLabel1 = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        ulicaField = new javax.swing.JTextField();
        nrdomuField = new javax.swing.JTextField();
        nrlokaluField = new javax.swing.JTextField();
        kodPocztowyField = new javax.swing.JFormattedTextField(format);
        pocztaField = new javax.swing.JTextField();
        miejscowoscField = new javax.swing.JTextField();
        kodLabel = new javax.swing.JLabel();
        krajField = new javax.swing.JTextField();
        niezgodneHasla = new javax.swing.JLabel();
        wypelnijPola = new javax.swing.JLabel();
        zamknij = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        imieField.setText("Imię");
        imieField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                imieFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                imieFieldFocusLost(evt);
            }
        });

        nazwiskoField.setText("Nazwisko");
        nazwiskoField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nazwiskoFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nazwiskoFieldFocusLost(evt);
            }
        });

        loginField.setText("Login");
        loginField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                loginFieldFocusLost(evt);
            }
        });

        hasloField.setText("Hasło");
        hasloField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                hasloFieldFocusGained(evt);
            }
        });

        powtorzField.setText("Hasło");
        powtorzField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                powtorzFieldFocusGained(evt);
            }
        });

        telefonField.setText("Telefon");
        telefonField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                telefonFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                telefonFieldFocusLost(evt);
            }
        });

        mailField.setText("Mail");
        mailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mailFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mailFieldFocusLost(evt);
            }
        });

        umowaField.setText("Umowa");
        umowaField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                umowaFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                umowaFieldFocusLost(evt);
            }
        });

        statusField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Sprzedawca", "Magazynier" }));
        statusField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusFieldActionPerformed(evt);
            }
        });

        utworz.setText("Dodaj");
        utworz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utworzActionPerformed(evt);
            }
        });

        hasloLabel.setText("Hasło:");

        hasloLabel1.setText("Powtórz hasło:");

        statusLabel.setText("Status:");

        titleLabel.setFont(new java.awt.Font("Vijaya", 0, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Dodawanie nowego pracownika");

        ulicaField.setText("Ulica");
        ulicaField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ulicaFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ulicaFieldFocusLost(evt);
            }
        });

        nrdomuField.setText("Nr domu");
        nrdomuField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nrdomuFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nrdomuFieldFocusLost(evt);
            }
        });

        nrlokaluField.setText("Nr lokalu");
        nrlokaluField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nrlokaluFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nrlokaluFieldFocusLost(evt);
            }
        });

        kodPocztowyField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                kodPocztowyFieldFocusGained(evt);
            }
        });

        pocztaField.setText("Poczta");
        pocztaField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pocztaFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pocztaFieldFocusLost(evt);
            }
        });

        miejscowoscField.setText("Miejscowość");
        miejscowoscField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                miejscowoscFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                miejscowoscFieldFocusLost(evt);
            }
        });

        kodLabel.setText("Kod pocztowy:");

        krajField.setText("Kraj");
        krajField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                krajFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                krajFieldFocusLost(evt);
            }
        });

        niezgodneHasla.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        niezgodneHasla.setForeground(new java.awt.Color(255, 0, 0));
        niezgodneHasla.setText("Podane hasła się nie zgadzają.");

        wypelnijPola.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        wypelnijPola.setForeground(new java.awt.Color(255, 0, 0));
        wypelnijPola.setText("Wypełnij wszystkie pola!");

        zamknij.setText("Zamknij");
        zamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zamknijActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(statusField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(252, 252, 252)
                                .addComponent(utworz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(loginField, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hasloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hasloField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(powtorzField, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(niezgodneHasla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(hasloLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ulicaField)
                                    .addGap(18, 18, 18)
                                    .addComponent(nrdomuField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(nrlokaluField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(kodLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(kodPocztowyField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(pocztaField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(umowaField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(telefonField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(mailField)))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(miejscowoscField, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                        .addComponent(krajField, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                        .addComponent(wypelnijPola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(imieField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nazwiskoField, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 7, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zamknij)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(zamknij)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(imieField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nazwiskoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ulicaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nrdomuField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nrlokaluField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kodLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pocztaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(miejscowoscField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kodPocztowyField))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telefonField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(krajField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(umowaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wypelnijPola))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hasloLabel)
                            .addComponent(hasloLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hasloField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(powtorzField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statusLabel)
                            .addComponent(niezgodneHasla))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(statusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(utworz))
                        .addGap(24, 24, 24))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void utworzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utworzActionPerformed
        
        niezgodneHasla.setVisible(false);
        wypelnijPola.setVisible(false);
        
        String[] inputStrings=new String[12];
        inputStrings[0]=imieField.getText();
        inputStrings[1]=nazwiskoField.getText();
        inputStrings[2]=ulicaField.getText();
        inputStrings[3]=kodPocztowyField.getText();
        inputStrings[4]=pocztaField.getText();
        inputStrings[5]=miejscowoscField.getText();
        inputStrings[6]=krajField.getText();
        inputStrings[7]=loginField.getText();
        inputStrings[8]=new String(hasloField.getPassword());
        inputStrings[9]=mailField.getText();
        inputStrings[10]=umowaField.getText();
        inputStrings[11]=statusField.getSelectedItem().toString();
        //System.out.println(inputStrings[7]);
        
        
        Integer[] inputInts=new Integer[3];
        try
        {
            inputInts[0]=new Integer(telefonField.getText());
            inputInts[1]=new Integer(nrdomuField.getText());
            inputInts[2]=new Integer(nrlokaluField.getText());
        }
        catch(Exception e)
        {
            wypelnijPola.setVisible(true);
            hasloField.setText("");
            powtorzField.setText("");
            return;
        }
        try
        {
            CallableStatement proc = connection.prepareCall("{call DodajPracownika(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)}");
            for (int i = 0; i<12;i++)
            {
                //System.out.println(inputStrings[i]);
                if(inputStrings[i].equals(""))
                {
                    wypelnijPola.setVisible(true);
                    hasloField.setText("");
                    powtorzField.setText("");
                    return;
                }
                proc.setString(i+1, inputStrings[i]);
            }
            for (int i = 0; i<3; i++)
            {
                proc.setInt(i+13, inputInts[i]);
            }
            
            if(!inputStrings[8].equals(new String(powtorzField.getPassword())))
            {
                System.out.println("Hasło"+inputStrings[8]+" != "+powtorzField.getPassword().toString());
                niezgodneHasla.setVisible(true);
                hasloField.setText("");
                powtorzField.setText("");
                return;
            }
            
            proc.execute();
            proc.close();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        finally
        {
            //dispose();
        }
    }//GEN-LAST:event_utworzActionPerformed

    private void statusFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusFieldActionPerformed

    private void imieFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_imieFieldFocusGained
        imieField.selectAll();
    }//GEN-LAST:event_imieFieldFocusGained

    private void nazwiskoFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nazwiskoFieldFocusGained
        nazwiskoField.selectAll();
    }//GEN-LAST:event_nazwiskoFieldFocusGained

    private void ulicaFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ulicaFieldFocusGained
        ulicaField.selectAll();
    }//GEN-LAST:event_ulicaFieldFocusGained

    private void nrdomuFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nrdomuFieldFocusGained
        nrdomuField.selectAll();
    }//GEN-LAST:event_nrdomuFieldFocusGained

    private void nrlokaluFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nrlokaluFieldFocusGained
        nrlokaluField.selectAll();
    }//GEN-LAST:event_nrlokaluFieldFocusGained

    private void kodPocztowyFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kodPocztowyFieldFocusGained
        kodPocztowyField.selectAll();
    }//GEN-LAST:event_kodPocztowyFieldFocusGained

    private void pocztaFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pocztaFieldFocusGained
        pocztaField.selectAll();
    }//GEN-LAST:event_pocztaFieldFocusGained

    private void miejscowoscFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_miejscowoscFieldFocusGained
        miejscowoscField.selectAll();
    }//GEN-LAST:event_miejscowoscFieldFocusGained

    private void telefonFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonFieldFocusGained
        telefonField.selectAll();
    }//GEN-LAST:event_telefonFieldFocusGained

    private void mailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailFieldFocusGained
        mailField.selectAll();
    }//GEN-LAST:event_mailFieldFocusGained

    private void krajFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_krajFieldFocusGained
        krajField.selectAll();
    }//GEN-LAST:event_krajFieldFocusGained

    private void umowaFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_umowaFieldFocusGained
        umowaField.selectAll();
    }//GEN-LAST:event_umowaFieldFocusGained

    private void loginFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginFieldFocusGained
        loginField.selectAll();
    }//GEN-LAST:event_loginFieldFocusGained

    private void hasloFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hasloFieldFocusGained
        hasloField.selectAll();
    }//GEN-LAST:event_hasloFieldFocusGained

    private void powtorzFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_powtorzFieldFocusGained
        powtorzField.selectAll();
    }//GEN-LAST:event_powtorzFieldFocusGained

    private void imieFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_imieFieldFocusLost
        if(imieField.getText().equals(""))
        {
            imieField.setText("Imię");
        }
    }//GEN-LAST:event_imieFieldFocusLost

    private void nazwiskoFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nazwiskoFieldFocusLost
        if(nazwiskoField.getText().equals(""))
        {
            nazwiskoField.setText("Nazwisko");
        }
    }//GEN-LAST:event_nazwiskoFieldFocusLost

    private void ulicaFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ulicaFieldFocusLost
        if(ulicaField.getText().equals(""))
        {
            ulicaField.setText("Ulica");
        }
    }//GEN-LAST:event_ulicaFieldFocusLost

    private void nrdomuFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nrdomuFieldFocusLost
        if(nrdomuField.getText().equals(""))
        {
            nrdomuField.setText("Nr domu");
        }
    }//GEN-LAST:event_nrdomuFieldFocusLost

    private void nrlokaluFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nrlokaluFieldFocusLost
        if(nrlokaluField.getText().equals(""))
        {
            nrlokaluField.setText("Nr lokalu");
        }
    }//GEN-LAST:event_nrlokaluFieldFocusLost

    private void pocztaFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pocztaFieldFocusLost
        if(pocztaField.getText().equals(""))
        {
            pocztaField.setText("Poczta");
        }
    }//GEN-LAST:event_pocztaFieldFocusLost

    private void miejscowoscFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_miejscowoscFieldFocusLost
        if(miejscowoscField.getText().equals(""))
        {
            miejscowoscField.setText("Miejscowość");
        }
    }//GEN-LAST:event_miejscowoscFieldFocusLost

    private void telefonFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonFieldFocusLost
        if(telefonField.getText().equals(""))
        {
            telefonField.setText("Telefon");
        }
    }//GEN-LAST:event_telefonFieldFocusLost

    private void mailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailFieldFocusLost
        if(mailField.getText().equals(""))
        {
            mailField.setText("Mail");
        }
    }//GEN-LAST:event_mailFieldFocusLost

    private void krajFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_krajFieldFocusLost
        if(krajField.getText().equals(""))
        {
            krajField.setText("Kraj");
        }
    }//GEN-LAST:event_krajFieldFocusLost

    private void umowaFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_umowaFieldFocusLost
        if(umowaField.getText().equals(""))
        {
            umowaField.setText("Umowa");
        }
    }//GEN-LAST:event_umowaFieldFocusLost

    private void loginFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginFieldFocusLost
        if(loginField.getText().equals(""))
        {
            loginField.setText("Login");
        }
    }//GEN-LAST:event_loginFieldFocusLost

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void zamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zamknijActionPerformed
        dispose();
    }//GEN-LAST:event_zamknijActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void WzorceSklep(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new OknoDodajPracownika(connection).setVisible(true);
            }
        });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField hasloField;
    private javax.swing.JLabel hasloLabel;
    private javax.swing.JLabel hasloLabel1;
    private javax.swing.JTextField imieField;
    private javax.swing.JLabel kodLabel;
    private javax.swing.JFormattedTextField kodPocztowyField;
    private javax.swing.JTextField krajField;
    private javax.swing.JTextField loginField;
    private javax.swing.JTextField mailField;
    private javax.swing.JTextField miejscowoscField;
    private javax.swing.JTextField nazwiskoField;
    private javax.swing.JLabel niezgodneHasla;
    private javax.swing.JTextField nrdomuField;
    private javax.swing.JTextField nrlokaluField;
    private javax.swing.JTextField pocztaField;
    private javax.swing.JPasswordField powtorzField;
    private javax.swing.JComboBox statusField;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextField telefonField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField ulicaField;
    private javax.swing.JTextField umowaField;
    private javax.swing.JButton utworz;
    private javax.swing.JLabel wypelnijPola;
    private javax.swing.JButton zamknij;
    // End of variables declaration//GEN-END:variables
}
