/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package WzorceSklep.Data.Zamowienie;

import WzorceSklep.DAOFactory;
import WzorceSklep.Data.Klient.Klient;
import WzorceSklep.Data.Pracownik.Pracownik;
import WzorceSklep.Data.Produkt.Produkt;
import WzorceSklep.GUI.RefreshableJFrame;
import org.joda.time.DateTime;

import javax.swing.*;
import java.awt.*;
import java.util.List;
import java.sql.Date;
import java.sql.SQLException;

/**
 *
 * @author KrzysztofD
 */
public class NoweZamowienieKlientaDialog extends javax.swing.JDialog {

    private final Pracownik pracownik;
    private Klient[] klienci;
    private Produkt[] produkty;
    private final DAOFactory daoFactory;

    /**
     * Creates new form NoweZamowienieKlientaDialog
     */
    public NoweZamowienieKlientaDialog(Frame parent, Pracownik pracownik, DAOFactory daoFactory) {
        super(parent, true);
        this.pracownik = pracownik;
        this.daoFactory = daoFactory;
        initComponents();
        try {
            setComboBoxContents();
        } catch (SQLException e) {
            e.printStackTrace();  //To change body of catch statement use File | Settings | File Templates.
        }
        ProduktyComboBoxPropertyChange(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        KlientComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        ProduktyComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        IloscSpinner = new javax.swing.JSpinner(new SpinnerNumberModel(1,1,1,1));
        CancelButton = new javax.swing.JButton();
        OKButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Wybierz klienta:");

        KlientComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Wybierz produkt:");

        ProduktyComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ProduktyComboBox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                ProduktyComboBoxPropertyChange(evt);
            }
        });

        jLabel3.setText("Ilość:");

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        OKButton.setText("OK");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                    .addComponent(KlientComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProduktyComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(185, 185, 185)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(IloscSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(KlientComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProduktyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OKButton)
                            .addComponent(CancelButton)))
                    .addComponent(IloscSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        insertNewZamowienie();
        dispose();
    }//GEN-LAST:event_OKButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void ProduktyComboBoxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_ProduktyComboBoxPropertyChange
        int selectedIndex = ProduktyComboBox.getSelectedIndex();
        if(IloscSpinner==null || produkty==null || selectedIndex<0) return;
        SpinnerModel model = new SpinnerNumberModel(1, 1, produkty[selectedIndex].ilosc, 1);
        IloscSpinner.setModel(model);
    }//GEN-LAST:event_ProduktyComboBoxPropertyChange

    private void insertNewZamowienie() {
        ZamowienieKlienta zamowienieKlienta = new ZamowienieKlienta();
        zamowienieKlienta.tworzacy = pracownik;
        zamowienieKlienta.zamawiajacy = klienci[KlientComboBox.getSelectedIndex()];
        zamowienieKlienta.setProduktZamowiony(produkty[ProduktyComboBox.getSelectedIndex()]);
        zamowienieKlienta.setDataZamowienia(new Date(new DateTime().getMillis()));
        zamowienieKlienta.setIlosc((Integer) IloscSpinner.getValue());
        try {
            daoFactory.getZamowieniaKllientaDAO().insert(zamowienieKlienta);
            dispose();
        } catch (SQLException e) {
            e.printStackTrace();  //To change body of catch statement use File | Settings | File Templates.
        }
    }

    private void setComboBoxContents() throws SQLException {
        KlientComboBox.removeAllItems();
        ProduktyComboBox.removeAllItems();
        List<Klient> klientList = daoFactory.getKlientGetter().select();
        List<Produkt> produktList = daoFactory.getProduktGetter().select();
        klienci = klientList.toArray(new Klient[klientList.size()]);
        produkty = produktList.toArray(new Produkt[produktList.size()]);
        for (Klient klient : klientList) {
            String name = klient.getName();
            KlientComboBox.addItem(name);
        }
        for (Produkt produkt : produktList) {
            String name = produkt.ID + " " + produkt.nazwa;
            ProduktyComboBox.addItem(name);
        }
    }
    public static void show(final Pracownik pracownik, final DAOFactory factory, final RefreshableJFrame parent) {

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NoweZamowienieKlientaDialog dialog = new NoweZamowienieKlientaDialog(parent, pracownik, factory);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosed(java.awt.event.WindowEvent e) {
                        parent.refreshCurrentWindow();
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JSpinner IloscSpinner;
    private javax.swing.JComboBox<String> KlientComboBox;
    private javax.swing.JButton OKButton;
    private javax.swing.JComboBox<String> ProduktyComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
